services:
  - type: web
    name: sillyhacksmemegenerator
    env: python
    buildCommand:
      pip install -r requirements.txt
      apt-get update && apt-get install -y imagemagick libmagickwand-dev
    startCommand: gunicorn main:app